+incdir+rtl_shims
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/apf
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core
rtl_shims/mf_pllbase_sim.sv
rtl_shims/altsyncram_sim.sv
rtl_shims/dcfifo_sim.sv
rtl_shims/vendor_ip_stubs.sv
rtl_shims/pacman_mixed_language_stubs.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/apf/common.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/apf/mf_datatable.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/core_bridge_cmd.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/lib/data_loader.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/lib/data_unloader.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/lib/sync_fifo.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/lib/sound_i2s.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/lib/pocket_sync_bit.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/rtl/pause.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/rtl/hiscore.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/rtl/audio_filter.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/rtl/savestate/save_state_controller.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-PacMan/src/fpga/core/core_top.sv
