+incdir+rtl_shims
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/apf
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tv80
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/mem
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tools
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/video
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/audio
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/cpu
rtl_shims/mf_pllbase_sim.sv
rtl_shims/altsyncram_sim.sv
rtl_shims/dcfifo_sim.sv
rtl_shims/vendor_ip_stubs.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/apf/common.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/apf/mf_datatable.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/core_bridge_cmd.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/data_loader.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/data_unloader.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/sync_fifo.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/sound_i2s.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tools/clk_en.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tools/rising_edge.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tools/falling_edge.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/mem/ram.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/mem/dpram.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/mem/spram.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tv80/tv80_alu.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tv80/tv80_mcode.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tv80/tv80_reg.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tv80/tv80_core.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tv80/tv80n.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/tv80/tv80s.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/cpu/cpu_rom.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/cpu/cpu_ram.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/cpu/mcpu.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/video/hvgen.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/video/vdata.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/video/video.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/audio/sn76489_audio.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/audio/audio.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/jg_decode.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/core.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/mrjong.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/pause.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/rtl/hiscore.v
/Users/ericlewis/Developer/openfpga-arcade-cores/our-pocket-cores/openFPGA-MrJong/src/fpga/core/core_top.sv
