+incdir+rtl_shims
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/ref-pocket-cores/agg23/template/src/fpga/apf
+incdir+/Users/ericlewis/Developer/openfpga-arcade-cores/ref-pocket-cores/agg23/template/src/fpga/core
rtl_shims/mf_pllbase_sim.sv
rtl_shims/altsyncram_sim.sv
rtl_shims/dcfifo_sim.sv
rtl_shims/vendor_ip_stubs.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/ref-pocket-cores/agg23/template/src/fpga/apf/common.v
/Users/ericlewis/Developer/openfpga-arcade-cores/ref-pocket-cores/agg23/template/src/fpga/apf/mf_datatable.v
/Users/ericlewis/Developer/openfpga-arcade-cores/ref-pocket-cores/agg23/template/src/fpga/core/core_bridge_cmd.v
/Users/ericlewis/Developer/openfpga-arcade-cores/ref-pocket-cores/agg23/template/src/fpga/core/sync_fifo.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/ref-pocket-cores/agg23/template/src/fpga/core/sound_i2s.sv
/Users/ericlewis/Developer/openfpga-arcade-cores/ref-pocket-cores/agg23/template/src/fpga/core/core_top.v
