#!/usr/bin/env python3
"""Generate reviewable external-memory model scaffolds for apfsim profiles."""
from __future__ import annotations

import re
from typing import Any


WRAPPER_CLASSES = ("sram", "psram", "cram")
CLASS_MODULES = {
    "sram": "apfsim_async_sram_16_model",
    "psram": "apfsim_psram_like_model",
    "cram": "apfsim_cram_like_model",
}
CLASS_COUNTERS = {
    "sram": ["sram_read_count", "sram_write_count", "sram_bus_contention_error", "sram_byte_enable_error"],
    "psram": ["psram_read_count", "psram_write_count", "psram_overrun_error", "psram_byte_enable_error"],
    "cram": ["cram_read_count", "cram_write_count", "cram_overrun_error", "cram_byte_enable_error"],
}


def memory_wrapper_plan(memory: dict[str, Any] | None, *, path: str = "{profile_dir}/apfsim_memory_models.sv") -> dict[str, Any]:
    memory = memory if isinstance(memory, dict) else {}
    external = [str(item) for item in memory.get("external_classes", []) if str(item) in WRAPPER_CLASSES]
    classes = [item for item in WRAPPER_CLASSES if item in external]
    counters: list[str] = []
    modules: list[str] = []
    for cls in classes:
        modules.append(CLASS_MODULES[cls])
        counters.extend(CLASS_COUNTERS[cls])
    return {
        "schema": "apfsim.memory_wrapper_plan.v1",
        "generated": bool(classes),
        "path": path,
        "classes": classes,
        "modules": modules,
        "activity_counters": counters,
        "wire_required": bool(classes),
        "confidence": "scaffold_only" if classes else "not_required",
        "notes": (
            "Generated helper instantiates public memory models but must be wired by the generated/core wrapper "
            "before activity counters are live."
            if classes else
            "No external SRAM/PSRAM/CRAM wrapper scaffold required by discovery."
        ),
    }


def render_memory_wrapper_sv(
    memory: dict[str, Any] | None,
    *,
    module_name: str = "apfsim_generated_memory_models",
) -> str:
    """Render a standalone SystemVerilog helper module for selected external RAM classes."""
    plan = memory_wrapper_plan(memory)
    classes = plan["classes"]
    module_name = sanitize_sv_identifier(module_name)
    ports = ["    input  wire        clk", "    input  wire        reset"]
    blocks: list[str] = []

    if "sram" in classes:
        ports.extend([
            "    input  wire        sram_ce_n",
            "    input  wire        sram_oe_n",
            "    input  wire        sram_we_n",
            "    input  wire        sram_lb_n",
            "    input  wire        sram_ub_n",
            "    input  wire [23:0] sram_addr",
            "    inout  wire [15:0] sram_dq",
            "    output wire [31:0] sram_read_count",
            "    output wire [31:0] sram_write_count",
            "    output wire        sram_bus_contention_error",
            "    output wire        sram_byte_enable_error",
        ])
        blocks.append(
            """
    apfsim_async_sram_16_model #(
        .ADDR_WIDTH(24)
    ) sram_model (
        .clk(clk),
        .reset(reset),
        .ce_n(sram_ce_n),
        .oe_n(sram_oe_n),
        .we_n(sram_we_n),
        .lb_n(sram_lb_n),
        .ub_n(sram_ub_n),
        .addr(sram_addr),
        .dq(sram_dq),
        .read_count(sram_read_count),
        .write_count(sram_write_count),
        .bus_contention_error(sram_bus_contention_error),
        .byte_enable_error(sram_byte_enable_error)
    );
""".rstrip()
        )

    if "psram" in classes:
        ports.extend(transactional_ports("psram"))
        blocks.append(transactional_instance("psram", "apfsim_psram_like_model"))

    if "cram" in classes:
        ports.extend(transactional_ports("cram"))
        blocks.append(transactional_instance("cram", "apfsim_cram_like_model"))

    if not classes:
        blocks.append("    // No external RAM model was selected for this generated profile.")

    port_text = ",\n".join(ports)
    block_text = "\n\n".join(blocks)
    class_text = ", ".join(classes) or "none"
    return f"""// Generated by apfsim generate-profile.
// Purpose: reviewable external memory model scaffold for classes: {class_text}.
// This file is simulation-only and is not automatically wired into the core.

module {module_name} (
{port_text}
);

{block_text}

endmodule
"""


def transactional_ports(prefix: str) -> list[str]:
    return [
        f"    input  wire        {prefix}_req",
        f"    input  wire        {prefix}_we",
        f"    input  wire [23:0] {prefix}_addr",
        f"    input  wire [15:0] {prefix}_din",
        f"    input  wire [1:0]  {prefix}_byteena",
        f"    output wire [15:0] {prefix}_dout",
        f"    output wire        {prefix}_ack",
        f"    output wire        {prefix}_busy",
        f"    output wire [31:0] {prefix}_read_count",
        f"    output wire [31:0] {prefix}_write_count",
        f"    output wire        {prefix}_overrun_error",
        f"    output wire        {prefix}_byte_enable_error",
    ]


def transactional_instance(prefix: str, module: str) -> str:
    return f"""
    {module} #(
        .ADDR_WIDTH(24),
        .DATA_WIDTH(16)
    ) {prefix}_model (
        .clk(clk),
        .reset(reset),
        .req({prefix}_req),
        .we({prefix}_we),
        .addr({prefix}_addr),
        .din({prefix}_din),
        .byteena({prefix}_byteena),
        .dout({prefix}_dout),
        .ack({prefix}_ack),
        .busy({prefix}_busy),
        .read_count({prefix}_read_count),
        .write_count({prefix}_write_count),
        .overrun_error({prefix}_overrun_error),
        .byte_enable_error({prefix}_byte_enable_error)
    );
""".rstrip()


def sanitize_sv_identifier(value: str) -> str:
    text = re.sub(r"[^A-Za-z0-9_$]+", "_", value).strip("_")
    if not text or text[0].isdigit():
        text = f"apfsim_{text}"
    return text
