+incdir+rtl_shims
+incdir+/Users/ericlewis/Developer/core-example-basicassets/src/fpga/apf
+incdir+/Users/ericlewis/Developer/core-example-basicassets/src/fpga/core
+incdir+/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib
rtl_shims/mf_pllbase_sim.sv
rtl_shims/altsyncram_sim.sv
rtl_shims/basicassets_io_sdram_sim.v
rtl_shims/vendor_ip_stubs.sv
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/apf/common.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/apf/mf_datatable.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/core/core_bridge_cmd.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib/pocket_addr_decode.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib/pocket_async_fifo.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib/pocket_cdc_bit_pulse.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib/pocket_cdc_bus_mailbox.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib/pocket_reset_sync.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib/pocket_rr_arb_tree.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib/pocket_stream_reg.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/lib/pocket_sync_bit.v
/Users/ericlewis/Developer/core-example-basicassets/src/fpga/core/mf_linebuf.v
build/generated/basicassets_core_top_impl.v
rtl_shims/basicassets_core_top_wrapper.sv
